-- MySQL Script generated by MySQL Workbench
-- Tue Apr 25 19:09:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema autoservice
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema autoservice
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autoservice` DEFAULT CHARACTER SET utf8 ;
USE `autoservice` ;

-- -----------------------------------------------------
-- Table `autoservice`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoservice`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `fio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoservice`.`subscribers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoservice`.`subscribers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoservice`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoservice`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `photo_path` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoservice`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoservice`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categories_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `descrp` VARCHAR(300) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `photo_path` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_categories1_idx` (`categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `autoservice`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoservice`.`cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoservice`.`cards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cards_users_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_cards_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_cards_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `autoservice`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cards_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `autoservice`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
